# Generated by Django 2.2 on 2019-04-16 19:53

from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'initial_data', app_label='register')


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка машины',
                'verbose_name_plural': 'Марки машин',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название модели')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.CarBrand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель машины',
                'verbose_name_plural': 'Модели машин',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для выбора')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], unique=True, verbose_name='День недели')),
                ('is_workday', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('begin', models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня')),
            ],
            options={
                'verbose_name': 'Режим работы',
                'verbose_name_plural': 'Режим работы',
            },
        ),
        migrations.CreateModel(
            name='RegisterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fio', models.CharField(max_length=256, verbose_name='Клиент')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.CarBrand', verbose_name='Марка')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.CarModel', verbose_name='Модель')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Master', verbose_name='Мастер')),
            ],
        ),
        migrations.RunPython(load_fixture, reverse),
    ]

