# Generated by Django 2.2 on 2019-04-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerrecord',
            options={'ordering': ('-date',), 'verbose_name': 'Запись на диагностику', 'verbose_name_plural': 'Записи на диагностику'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('weekday',), 'verbose_name': 'Режим работы', 'verbose_name_plural': 'Режим работы'},
        ),
    ]
